{{ $defaultAppName := printf "%s" .Release.Name }}
{{ $fullAppName := default $defaultAppName .Values.fullNameOverride }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullAppName }}-secret
type: Opaque
data:
  NODE_ENV: {{ .Values.faucet.nodeEnv | b64enc }}
  PORT: {{ .Values.faucet.port | toString  | b64enc }}
  RIPPLED_URI: {{ .Values.faucet.rippledUri | b64enc }}
  FUNDING_ADDRESS: {{ .Values.faucet.fundingAddr | b64enc }}
  FUNDING_SECRET: {{ .Values.faucet.fundingSecret | b64enc }}
  XRP_AMOUNT: {{ .Values.faucet.xrpAmount | toString  | b64enc }}
  BIGQUERY_PRIVATE_KEY: {{ .Values.faucet.bigQueryPrivateKey | toString  | b64enc }}
  BIGQUERY_CLIENT_EMAIL: {{ .Values.faucet.bigQueryClientEmail | toString  | b64enc }}
  BIGQUERY_PROJECT_ID: {{ .Values.faucet.bigQueryProjectId | toString  | b64enc }}
  BIGQUERY_DATASET_ID: {{ .Values.faucet.bigQueryDatasetId | toString  | b64enc }}
  BIGQUERY_TABLE_ID: {{ .Values.faucet.bigQueryTableId | toString  | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullAppName }}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"443":{"name": "{{ $fullAppName }}-neg"}}}'
spec:
  type: ClusterIP
  selector:
    app: {{ $fullAppName }}
  ports:
  - protocol: TCP
    port: 443
    targetPort: {{ .Values.faucet.port }}
    name: public
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullAppName }}
spec:
  replicas: {{ .Values.faucet.replicas }}
  selector:
    matchLabels:
      app: {{ $fullAppName }}
  template:
    metadata:
      annotations:
        date: {{ now }}
      labels:
        app: {{ $fullAppName }}
    spec:
      containers:
      - image: {{ .Values.faucet.image }}
        name: {{ $fullAppName }}
        envFrom:
        - secretRef:
            name: {{ $fullAppName }}-secret
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.faucet.port }}
          name: public
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
