name: Run script on feature/release branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        description: branch name should start with "feature/" or "release/"
        required: true

jobs:
  trigger_component_build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/xpring-eng/ripplex-builder:0.1.42
    steps:
      - name: Check if feature branch
        id: validate_feature_branch
        if: startsWith(inputs.branch_name, 'feature/')
        run: |
          echo "valid_name=true" >> $GITHUB_OUTPUT
          echo "branch_prefix=feature" >> $GITHUB_ENV
      
      - name: Check if release branch
        id: validate_release_branch
        if: startsWith(inputs.branch_name, 'release/')
        run: |
          echo "valid_name=true" >> $GITHUB_OUTPUT
          echo "branch_prefix=release" >> $GITHUB_ENV
      
      - name: Validate prefix
        if: steps.validate_feature_branch.outputs.valid_name != 'true' && steps.validate_release_branch.outputs.valid_name != 'true'
        run: |
          echo "Not valid branch, branch should start with feature/ or release/"
          exit 1

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          path: base_repo
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.SA_PAT_PUSH }}
          set-safe-directory: true
     
      - name: Get current project_dir
        id: project_dir
        run: |
          echo "project_dir=$PWD" >> $GITHUB_OUTPUT
          echo "project_dir=$PWD"

      - name: Get version number from cicd.yaml
        id: version
        run: |
            project_dir="${{ steps.project_dir.outputs.project_dir }}"
            export version=$(yq e '.cicd.version' "${project_dir}/base_repo/cicd.yaml")
            echo "cicd.version: $version"
            if [ ! -n "${version}" ]; then
            echo "Version is empty. Please add a cicd.version to your cicd.yaml file."
            exit 1
            else
            echo "Version is $version"
            echo "version=$version" >> $GITHUB_OUTPUT
            echo "version=$version"
            fi

      - name: Checkout cicd-scripts repo
        uses: actions/checkout@v3
        with:
            repository: xpring-eng/ripplex-cicd-scripts
            ref: ${{ steps.version.outputs.version }}
            ssh-key: ${{ secrets.CICD_SSH_KEY }}
            path: ripplex-cicd-scripts

      - name: Sync files with rsync
        run: |
            project_dir="${{ steps.project_dir.outputs.project_dir }}"
            cd "${project_dir}"
            mkdir -p "${project_dir}/base_repo/.cicd"
            rsync -avzr "${project_dir}/ripplex-cicd-scripts/ripplex-cicd/.cicd/" "${project_dir}/base_repo/.cicd/"
            rsync -avz "${project_dir}/ripplex-cicd-scripts/ripplex-cicd/build.sh" "${project_dir}/base_repo/build.sh"
    
      - name: Install Python dependencies
        run: |
          cd "${{ steps.project_dir.outputs.project_dir }}/base_repo"
          python3 -m pip install --upgrade pip
          pip3 install --no-cache-dir -r requirements.txt
      
      - name: Trigger all component builds
        run: |
          cd "${{ steps.project_dir.outputs.project_dir }}/base_repo"
          git fetch --tags
          ./build.sh ${{ env.branch_prefix }} all